
import type { Property, PropertyType, ListingType } from './types';

const ONE_DAY_MS = 24 * 60 * 60 * 1000;

export const MOCK_PROPERTIES_INITIAL: Property[] = [
  {
    id: '1',
    title: 'Moderno Apartamento Céntrico',
    address: 'Calle Principal 123, Apt 4B',
    city: 'Metrópolis',
    price: 210000000,
    bedrooms: 2,
    bathrooms: 2,
    area: 111, 
    type: 'Apartamento',
    listingType: 'Venta',
    description: 'Impresionante apartamento de 2 habitaciones en el corazón del centro. Cuenta con una sala de estar de concepto abierto, cocina actualizada con electrodomésticos de acero inoxidable y un balcón privado con vistas a la ciudad. Las comodidades del edificio incluyen un gimnasio y una terraza en la azotea.',
    images: [
      'https://placehold.co/800x600.png?text=Sala+Apartamento+Moderno',
      'https://placehold.co/600x400.png?text=Cocina+Apartamento',
      'https://placehold.co/600x400.png?text=Habitacion+Apartamento',
      'https://placehold.co/600x400.png?text=Vista+Balcon+Apartamento',
    ],
    isFeatured: true,
    agent: {
      name: 'Alicia Maravillas',
      phone: '555-123-4567',
      email: 'alicia.m@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agente+A',
    },
    features: ['Concepto Abierto', 'Cocina Actualizada', 'Balcón Privado', 'Gimnasio', 'Terraza en Azotea'],
    yearBuilt: 2018,
    lotSize: 0,
    createdAt: Date.now() - (ONE_DAY_MS * 5), 
    ownerId: 'system-agent-1',
  },
  {
    id: '2',
    title: 'Espaciosa Casa Familiar en Alquiler',
    address: 'Avenida del Roble 456',
    city: 'Suburbia',
    price: 1200000, // Price for rent
    bedrooms: 4,
    bathrooms: 3,
    area: 232, 
    type: 'Casa',
    listingType: 'Alquiler',
    description: 'Hermosa y espaciosa casa familiar de 4 habitaciones en un vecindario tranquilo y amigable. Amplio patio trasero con terraza, perfecto para el entretenimiento. Cocina moderna, pisos de madera en toda la casa y un garaje para dos autos. Se alquila por mes.',
    images: [
      'https://placehold.co/800x600.png?text=Exterior+Casa+Familiar',
      'https://placehold.co/600x400.png?text=Sala+Casa',
      'https://placehold.co/600x400.png?text=Cocina+Casa',
      'https://placehold.co/600x400.png?text=Patio+Trasero+Casa',
    ],
    isFeatured: true,
    agent: {
      name: 'Roberto Constructor',
      phone: '555-987-6543',
      email: 'roberto.c@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agente+B',
    },
    features: ['Amplio Patio Trasero', 'Terraza', 'Cocina Moderna', 'Pisos de Madera', 'Garaje para Dos Autos'],
    yearBuilt: 2005,
    lotSize: 697, 
    createdAt: Date.now() - (ONE_DAY_MS * 10), 
    ownerId: 'system-agent-2',
  },
  {
    id: '3',
    title: 'Condominio Urbano Chic',
    address: 'Calle del Pino 789, Unidad 1205',
    city: 'Metrópolis',
    price: 288000000,
    bedrooms: 1,
    bathrooms: 1,
    area: 79, 
    type: 'Condominio',
    listingType: 'Venta',
    description: 'Elegante condominio de 1 habitación con impresionantes vistas a la ciudad. Ventanas de piso a techo, cocina gourmet y acceso a comodidades premium del edificio que incluyen piscina, gimnasio y servicio de conserjería.',
    images: [
      'https://placehold.co/800x600.png?text=Interior+Condominio+Chic',
      'https://placehold.co/600x400.png?text=Vista+Condominio',
      'https://placehold.co/600x400.png?text=Cocina+Condominio',
    ],
    agent: {
      name: 'Carolina Danvers',
      phone: '555-111-2222',
      email: 'carolina.d@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agente+C'
    },
    features: ['Vistas a la Ciudad', 'Ventanas de Piso a Techo', 'Cocina Gourmet', 'Piscina', 'Gimnasio', 'Conserjería'],
    yearBuilt: 2020,
    createdAt: Date.now() - (ONE_DAY_MS * 2), 
    ownerId: 'system-agent-3',
  },
  {
    id: '4',
    title: 'Acogedor Adosado con Jardín (Alquiler)',
    address: 'Camino de las Flores 101',
    city: 'Valleverde',
    price: 950000, // Price for rent
    bedrooms: 3,
    bathrooms: 2.5,
    area: 167, 
    type: 'Adosado',
    listingType: 'Alquiler',
    description: 'Encantador adosado de 3 habitaciones con jardín privado, interiores actualizados y un parque comunitario. Ideal para familias o aquellos que buscan una mezcla de confort y conveniencia. Disponible para alquiler mensual.',
    images: [
      'https://placehold.co/800x600.png?text=Exterior+Adosado',
      'https://placehold.co/600x400.png?text=Jardin+Adosado',
      'https://placehold.co/600x400.png?text=Sala+Adosado',
    ],
    isFeatured: true,
    agent: {
      name: 'David Cobrecampo',
      phone: '555-333-4444',
      email: 'david.c@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agente+D',
    },
    features: ['Jardín Privado', 'Interiores Actualizados', 'Parque Comunitario', 'Chimenea'],
    yearBuilt: 1998,
    lotSize: 204, 
    createdAt: Date.now() - (ONE_DAY_MS * 7),
    ownerId: 'system-agent-4',
  },
  {
    id: '5',
    title: 'Suite Penthouse de Lujo',
    address: 'Torre Cielo Alto 99, PH1',
    city: 'Metrópolis',
    price: 750000000,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 297, 
    type: 'Apartamento',
    listingType: 'Venta',
    description: 'Experimente un lujo sin igual en esta exquisita suite penthouse. Vistas panorámicas de la ciudad, amplia terraza, acabados de diseñador y comodidades exclusivas del edificio.',
    images: [
      'https://placehold.co/800x600.png?text=Sala+Penthouse',
      'https://placehold.co/600x400.png?text=Terraza+Penthouse',
      'https://placehold.co/600x400.png?text=Habitacion+Principal+Penthouse',
    ],
    agent: {
      name: 'Eva Monedita',
      phone: '555-555-0070',
      email: 'eva.m@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agente+E'
    },
    features: ['Vistas Panorámicas', 'Amplia Terraza', 'Acabados de Diseñador', 'Ascensor Privado', 'Hogar Inteligente'],
    yearBuilt: 2022,
    createdAt: Date.now() - (ONE_DAY_MS * 1), 
    ownerId: 'system-agent-5',
  },
];

export const PROPERTY_TYPES: PropertyType[] = ["Casa", "Apartamento", "Condominio", "Adosado", "Terreno"];
export const LISTING_TYPES: ListingType[] = ["Venta", "Alquiler"];
export const CITIES: string[] = ["Metrópolis", "Suburbia", "Valleverde", "VistaOceano", "CrestaMontana", "San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón"];
