import type { Property, PropertyType } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Apartment',
    address: '123 Main St, Apt 4B',
    city: 'Metropolis',
    price: 350000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    type: 'Apartment',
    description: 'Stunning 2-bedroom apartment in the heart of downtown. Features an open-concept living area, updated kitchen with stainless steel appliances, and a private balcony with city views. Building amenities include a fitness center and rooftop terrace.',
    images: [
      'https://placehold.co/800x600.png?text=Modern+Apartment+Living+Room',
      'https://placehold.co/600x400.png?text=Apartment+Kitchen',
      'https://placehold.co/600x400.png?text=Apartment+Bedroom',
      'https://placehold.co/600x400.png?text=Apartment+Balcony+View',
    ],
    isFeatured: true,
    agent: {
      name: 'Alice Wonderland',
      phone: '555-123-4567',
      email: 'alice.w@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agent+A',
    },
    features: ['Open Concept', 'Updated Kitchen', 'Private Balcony', 'Fitness Center', 'Rooftop Terrace'],
    yearBuilt: 2018,
    lotSize: 0, // N/A for apartments typically
  },
  {
    id: '2',
    title: 'Spacious Family House',
    address: '456 Oak Ave',
    city: 'Suburbia',
    price: 650000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    type: 'House',
    description: 'Beautiful and spacious 4-bedroom family home in a quiet, friendly neighborhood. Large backyard with a deck, perfect for entertaining. Modern kitchen, hardwood floors throughout, and a two-car garage.',
    images: [
      'https://placehold.co/800x600.png?text=Family+House+Exterior',
      'https://placehold.co/600x400.png?text=House+Living+Room',
      'https://placehold.co/600x400.png?text=House+Kitchen',
      'https://placehold.co/600x400.png?text=House+Backyard',
    ],
    isFeatured: true,
    agent: {
      name: 'Bob The Builder',
      phone: '555-987-6543',
      email: 'bob.b@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agent+B',
    },
    features: ['Large Backyard', 'Deck', 'Modern Kitchen', 'Hardwood Floors', 'Two-Car Garage'],
    yearBuilt: 2005,
    lotSize: 7500,
  },
  {
    id: '3',
    title: 'Chic Urban Condo',
    address: '789 Pine Ln, Unit 1205',
    city: 'Metropolis',
    price: 480000,
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    type: 'Condo',
    description: 'Stylish 1-bedroom condo with breathtaking city views. Floor-to-ceiling windows, gourmet kitchen, and access to premium building amenities including a pool, gym, and concierge service.',
    images: [
      'https://placehold.co/800x600.png?text=Chic+Condo+Interior',
      'https://placehold.co/600x400.png?text=Condo+View',
      'https://placehold.co/600x400.png?text=Condo+Kitchen',
    ],
    agent: {
      name: 'Carol Danvers',
      phone: '555-111-2222',
      email: 'carol.d@example.com',
    },
    features: ['City Views', 'Floor-to-Ceiling Windows', 'Gourmet Kitchen', 'Pool', 'Gym', 'Concierge'],
    yearBuilt: 2020,
  },
  {
    id: '4',
    title: 'Cozy Townhouse with Garden',
    address: '101 Blossom Rd',
    city: 'Greenvalley',
    price: 420000,
    bedrooms: 3,
    bathrooms: 2.5,
    area: 1800,
    type: 'Townhouse',
    description: 'Charming 3-bedroom townhouse featuring a private garden, updated interiors, and a community park. Ideal for families or those seeking a blend of comfort and convenience.',
    images: [
      'https://placehold.co/800x600.png?text=Townhouse+Exterior',
      'https://placehold.co/600x400.png?text=Townhouse+Garden',
      'https://placehold.co/600x400.png?text=Townhouse+Living',
    ],
    isFeatured: true,
    agent: {
      name: 'David Copperfield',
      phone: '555-333-4444',
      email: 'david.c@example.com',
      avatarUrl: 'https://placehold.co/100x100.png?text=Agent+D',
    },
    features: ['Private Garden', 'Updated Interiors', 'Community Park', 'Fireplace'],
    yearBuilt: 1998,
    lotSize: 2200,
  },
  {
    id: '5',
    title: 'Luxury Penthouse Suite',
    address: '99 Sky High Tower, PH1',
    city: 'Metropolis',
    price: 1250000,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 3200,
    type: 'Apartment',
    description: 'Experience unparalleled luxury in this exquisite penthouse suite. Panoramic city views, expansive terrace, designer finishes, and exclusive building amenities.',
    images: [
      'https://placehold.co/800x600.png?text=Penthouse+Living+Area',
      'https://placehold.co/600x400.png?text=Penthouse+Terrace',
      'https://placehold.co/600x400.png?text=Penthouse+Master+Bedroom',
    ],
    agent: {
      name: 'Eve MoneyPenny',
      phone: '555-555-0070',
      email: 'eve.m@example.com',
    },
    features: ['Panoramic Views', 'Expansive Terrace', 'Designer Finishes', 'Private Elevator', 'Smart Home'],
    yearBuilt: 2022,
  },
];

export const PROPERTY_TYPES: PropertyType[] = ["House", "Apartment", "Condo", "Townhouse", "Land"];

export const CITIES: string[] = ["Metropolis", "Suburbia", "Greenvalley", "Oceanview", "Mountain Ridge"];
